### ISSUE TITLE
Can you add more comments?

### ISSUE THREAD

**Issue by MyPCIsBetter** [Joisar/LockScreenApp#3]
I mean: I don't really understand how you've done this "auto opening activity" when user push the power button. On stackoverflow are many questions about that, but no one really can explain how it works.

**Comment by frafrichile** [comment]
Indeed, very interesting app

**Comment by Joisar** [comment]
@MyPCIsBetter @frafrichile : I have committed stable version of app code. Kindly check it out. I have added the comments for better understanding.
