### ISSUE TITLE
Fix pls "IllegalArgumentException: Window type can not be changed after the window is added" in android 4+

### ISSUE THREAD

**Issue by v4ekmarev** [Joisar/LockScreenApp#4]
public void onCreate(Bundle savedInstanceState) {
        this.getWindow().setType(
                WindowManager.LayoutParams.TYPE_KEYGUARD_DIALOG
                        | WindowManager.LayoutParams.FLAG_FULLSCREEN);
        super.onAttachedToWindow();
        super.onCreate(savedInstanceState);
        getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON | WindowManager.LayoutParams.FLAG_SHOW_WHEN_LOCKED | WindowManager.LayoutParams.FLAG_FULLSCREEN);
        setContentView(R.layout.layout);

**Comment by Joisar** [comment]
@v4ekmarev : Thanks for reporting. I have committed stable version of the app code recently. Check it out.

**Comment by v4ekmarev** [comment]
It works, thanks. I found another solution, but it is your decision, I prefer
