### ISSUE TITLE
System lock screen appering

### ISSUE THREAD

**Issue by navanneethan** [Joisar/LockScreenApp#6]
Hi,

If i am having system lock and this app. After locking the devices i am getting both lock screen.

**Comment by Joisar** [comment]
Hi, It doesn't serve that purpose. You need to create admin of the device and work with its API. For reference, you may checkout following:

http://developer.android.com/guide/topics/admin/device-admin.html#sample
http://developer.android.com/reference/android/app/admin/DevicePolicyManager.html#lockNow()
